# Generated by Django 3.1.4 on 2020-12-22 20:14

from django.db import migrations


def add_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='generic')


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=migrations.RunPython.noop)
    ]
