# Generated by Django 3.1.4 on 2021-01-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210119_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.TextField(max_length=4096),
        ),
    ]
